### PR TITLE
[setup] pin down redis to avoid 4.0 breaking changes

### PR DESCRIPTION
**Pull request by arthurlogilab**

### CODE REVIEW

**Comment by jvanasco** [comment]
Do you know what the breaking changes are?  1.6.2 was intended to address the deprecation of charset and encoding.  If that is it, I'll look to a release that can better handle the defaults now that 4.0 is out.

**Comment by arthurlogilab** [comment]
Haven't looked into the details of the breaking changes no. They might be documented in the release notes : https://github.com/redis/redis-py/releases 

This might not be an ideal solution. I know that we had to do this pinning on a few applications that depend on pyramid-session-redis , but we'd prefer other users to benefit and not have that extra pinning.

**Comment by jvanasco** [comment]
I am releasing a new version to detect Redis and try to do what's right based on the install, but there is no incompatibility and pinning is not the correct solution.  Redis deprecated two arguments a while back and emitted Warnings about it.  A previous release of this library supported the new arguments, and emitted Warnings as well.  

The only times Redis will raise this error, is when users ignore warnings from both packages to use the new kwargs.

**Comment by arthurlogilab** [comment]
@jvanasco good news, thanks for maintaining this project :pray:

**Pull request closed without merging**
